name: Build and Release Magisk Module

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip Module
        run: |
          mkdir output
          zip -r output/OnePlusShare-Magisk.zip . -x ".git/*" -x ".github/*"

      - name: Create Release and Upload
        uses: softprops/action-gh-release@v1
        with:
          name: OnePlusShare Magisk Module
          tag_name: ${{ github.ref_name }}
          files: output/OnePlusShare-Magisk.zip
        env:
          GITHUB_TOKEN: ${{ secrets.ONEPLUSSHARE_GITHUB_TOKEN }}
